USE Adam882094;

CREATE TABLE registerUsers
(userId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
email VARCHAR(100) NOT NULL,
fname VARCHAR(100) NOT NULL,
lname VARCHAR(100) NOT NULL,
password VARCHAR(128) NOT NULL);

SELECT * FROM registerUsers;

CREATE TABLE webpages
(webpageId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
pageName VARCHAR(100) NOT NULL,
pageDesc VARCHAR(500) NOT NULL
);

SELECT * FROM webpages;

CREATE TABLE photo
(photoId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
photoUrl VARCHAR(500) NOT NULL
);

SELECT * FROM photo;